# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(524, 773)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.categorysortbox = QtWidgets.QGroupBox(self.centralwidget)
        self.categorysortbox.setGeometry(QtCore.QRect(10, 10, 501, 171))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.categorysortbox.setFont(font)
        self.categorysortbox.setStyleSheet("GroupBox {\n"
"    font: 75 11pt \"Book Antiqua\";\n"
"}")
        self.categorysortbox.setObjectName("categorysortbox")
        self.comboBox = QtWidgets.QComboBox(self.categorysortbox)
        self.comboBox.setGeometry(QtCore.QRect(150, 50, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.categorysortbox)
        self.label.setGeometry(QtCore.QRect(10, 50, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 524, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.fileLoad = QtWidgets.QAction(MainWindow)
        self.fileLoad.setObjectName("fileLoad")
        self.menuFile.addAction(self.fileLoad)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sorter"))
        self.categorysortbox.setTitle(_translate("MainWindow", "Category-Sort"))
        self.comboBox.setItemText(0, _translate("MainWindow", "All"))
        self.label.setText(_translate("MainWindow", "Department"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.fileLoad.setText(_translate("MainWindow", "Load"))
